### ISSUE TITLE
support passing arguments to PT program 

### ISSUE THREAD

**Issue by r0n1am** [twisteroidambassador/ptadapter#2]
For obfs4proxy, I could pass arguments to enable logging:

```
[ronlam@localhost pluggabletransportadapter]$ obfs4proxy --help
Usage of obfs4proxy:
  -enableLogging
        Log to TOR_PT_STATE_LOCATION/obfs4proxy.log
  -logLevel string
        Log level (ERROR/WARN/INFO/DEBUG) (default "ERROR")
  -obfs4-distBias
        Enable obfs4 using ScrambleSuit style table generation
  -unsafeLogging
        Disable the address scrubber
  -version
        Print version and exit
```

But using the script to pass arguments will cause error:

```
[ronlam@localhost pluggabletransportadapter]$ ./standalone_server.py standalone_server_config.ini -vv
[2016-08-24 14:13:16,839] root   DEBUG    Verbosity level set
[2016-08-24 14:13:16,839] root   DEBUG    Arguments:
[2016-08-24 14:13:16,839] root   DEBUG    Namespace(configfile=<_io.TextIOWrapper name='standalone_server_config.ini' mode='r' encoding='UTF-8'>, verbose=2)
[2016-08-24 14:13:16,840] root   INFO     Read config file
[2016-08-24 14:13:16,840] root   DEBUG    Transports:
[2016-08-24 14:13:16,840] root   DEBUG    {'obfs4': {'bindaddr': '127.0.0.1:7900'}}
[2016-08-24 14:13:16,840] pluggabletransportadapter INFO     Environment variables prepared for server /usr/local/bin/obfs4proxy -enableLogging
[2016-08-24 14:13:16,840] pluggabletransportadapter DEBUG    Environment variables:
[2016-08-24 14:13:16,840] pluggabletransportadapter DEBUG    {'TOR_PT_ORPORT': '127.0.0.1:7000', 'TOR_PT_SERVER_BINDADDR': 'obfs4-127.0.0.1:7900', 'TOR_PT_MANAGED_TRANSPORT_VER': '1', 'TOR_PT_STATE_LOCATION': '/tmp/.pt-state', 'TOR_PT_SERVER_TRANSPORTS': 'obfs4'}
Traceback (most recent call last):
  File "./standalone_server.py", line 91, in <module>
    main_cli()
  File "./standalone_server.py", line 73, in main_cli
    server.start()
  File "/home/ronlam/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py", line 187, in start
    self.run_ptexec()
  File "/home/ronlam/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py", line 49, in run_ptexec
    env=self.env, universal_newlines=True)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/obfs4proxy -enableLogging'
```

standalone_server_config.ini :

```
[ronlam@localhost pluggabletransportadapter]$ cat standalone_server_config.ini
[common]
exec = /usr/local/bin/obfs4proxy -enableLogging
statedir = /tmp/.pt-state
forward = 127.0.0.1:7000

[transports]
obfs4 = 127.0.0.1:7900
```

As stated in code, the standalone_server.py use subprocess.Popen(). The script pass whole '/usr/local/bin/obfs4proxy -enableLogging' as string, so the problem occurred. 

May this script possible to use something like shlex.split() to split exec string to list before passing to the subprocess.Popen()?

**Comment by twisteroidambassador** [comment]
Good idea, and shouldn't be too hard to implement.

**Comment by twisteroidambassador** [comment]
Done. 

On Windows `Popen()` takes strings directly, and I would like to avoid sending a string through `shlex.split()` only to have the parts reassembled, so the split will only be done for non-Windows operating systems.

**Comment by r0n1am** [comment]
I hate to say that, but the script failed to run after update.

```
[ronlam@localhost pluggabletransportadapter]$ ./standalone_server.py standalone_server_config.iniTraceback (most recent call last):
  File "./standalone_server.py", line 91, in <module>
    main_cli()
  File "./standalone_server.py", line 72, in main_cli
    server = PluggableTransportServerAdapter(ptexec, statedir, orport, transports)
  File "/home/ronlam/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py", line 185, in __init__
    self.ptexec)
TypeError: Can't convert 'list' object to str implicitly
[ronlam@localhost pluggabletransportadapter]$ ./standalone_server.py standalone_server_config.ini
Traceback (most recent call last):
  File "./standalone_server.py", line 91, in <module>
    main_cli()
  File "./standalone_server.py", line 72, in main_cli
    server = PluggableTransportServerAdapter(ptexec, statedir, orport, transports)
  File "/home/ronlam/pluggabletransportadapter/pluggabletransportadapter/baseserverclient.py", line 185, in __init__
    self.ptexec)
TypeError: Can't convert 'list' object to str implicitly
```

Seems because of the logging for self.ptexec.

**Comment by twisteroidambassador** [comment]
Welp, such is the danger of committing code without testing on the actual platform. The bug is indeed with logging, where it tries to concatenate a string with `ptexec` which is no longer a string but a list. It should be fixed now, so please try the new version.

**Comment by r0n1am** [comment]
Tested on my Mac, works like a charm now, Thanks! 

BTW, have to say love your scripts as your scripts have no other dependencies.
